# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstLeftPane = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstLeftPane.sizePolicy().hasHeightForWidth())
        self.lstLeftPane.setSizePolicy(sizePolicy)
        self.lstLeftPane.setMinimumSize(QtCore.QSize(100, 0))
        self.lstLeftPane.setObjectName("lstLeftPane")
        self.horizontalLayout.addWidget(self.lstLeftPane)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.tblRightPane = QtWidgets.QTableView(self.centralwidget)
        self.tblRightPane.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tblRightPane.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblRightPane.setSortingEnabled(True)
        self.tblRightPane.setObjectName("tblRightPane")
        self.horizontalLayout.addWidget(self.tblRightPane)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAuthors = QtWidgets.QMenu(self.menubar)
        self.menuAuthors.setObjectName("menuAuthors")
        self.menuPapers = QtWidgets.QMenu(self.menubar)
        self.menuPapers.setObjectName("menuPapers")
        self.menuCategories = QtWidgets.QMenu(self.menubar)
        self.menuCategories.setObjectName("menuCategories")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_paper = QtWidgets.QAction(MainWindow)
        self.actionAdd_paper.setObjectName("actionAdd_paper")
        self.actionRemove_paper = QtWidgets.QAction(MainWindow)
        self.actionRemove_paper.setObjectName("actionRemove_paper")
        self.actionEdit_paper = QtWidgets.QAction(MainWindow)
        self.actionEdit_paper.setObjectName("actionEdit_paper")
        self.actionAdd_author = QtWidgets.QAction(MainWindow)
        self.actionAdd_author.setObjectName("actionAdd_author")
        self.actionEdit_author = QtWidgets.QAction(MainWindow)
        self.actionEdit_author.setObjectName("actionEdit_author")
        self.actionRemove_author = QtWidgets.QAction(MainWindow)
        self.actionRemove_author.setObjectName("actionRemove_author")
        self.actionAdd_category = QtWidgets.QAction(MainWindow)
        self.actionAdd_category.setObjectName("actionAdd_category")
        self.actionEdit_category = QtWidgets.QAction(MainWindow)
        self.actionEdit_category.setObjectName("actionEdit_category")
        self.actionRemove_category = QtWidgets.QAction(MainWindow)
        self.actionRemove_category.setObjectName("actionRemove_category")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAuthors.addAction(self.actionAdd_author)
        self.menuAuthors.addAction(self.actionEdit_author)
        self.menuAuthors.addAction(self.actionRemove_author)
        self.menuPapers.addAction(self.actionAdd_paper)
        self.menuPapers.addAction(self.actionEdit_paper)
        self.menuPapers.addAction(self.actionRemove_paper)
        self.menuCategories.addAction(self.actionAdd_category)
        self.menuCategories.addAction(self.actionEdit_category)
        self.menuCategories.addAction(self.actionRemove_category)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPapers.menuAction())
        self.menubar.addAction(self.menuAuthors.menuAction())
        self.menubar.addAction(self.menuCategories.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Library"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuAuthors.setTitle(_translate("MainWindow", "&Authors"))
        self.menuPapers.setTitle(_translate("MainWindow", "&Papers"))
        self.menuCategories.setTitle(_translate("MainWindow", "&Categories"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionAdd_paper.setText(_translate("MainWindow", "&Add paper"))
        self.actionRemove_paper.setText(_translate("MainWindow", "&Remove paper"))
        self.actionEdit_paper.setText(_translate("MainWindow", "&Edit paper"))
        self.actionAdd_author.setText(_translate("MainWindow", "&Add author"))
        self.actionEdit_author.setText(_translate("MainWindow", "&Edit author"))
        self.actionRemove_author.setText(_translate("MainWindow", "&Remove author"))
        self.actionAdd_category.setText(_translate("MainWindow", "&Add category"))
        self.actionEdit_category.setText(_translate("MainWindow", "&Edit category"))
        self.actionRemove_category.setText(_translate("MainWindow", "&Remove category"))

